"""Task planner — decides what improvement the next session should pursue.

Runs at the end of every loop iteration AND can be invoked manually
(`suno-plan`). Reads state and recent history; writes a markdown task
description to NEXT_TASK.md that a human or future Claude session can pick up.

Decision rules are deliberately simple and readable — bump them when the
heuristics fail in practice. Not magic, just observable trends.
"""
from __future__ import annotations

import os
from datetime import datetime, timezone
from pathlib import Path

from suno.orchestrator import state as state_module
from suno.paths import LOG_DIR, NEXT_TASK_FILE


def _recent_wer_trend(history: list[dict], window: int = 5) -> str:
    """Returns 'improving' | 'plateau' | 'regressing' | 'insufficient'."""
    wers = [h["wer"] for h in history[-window:] if h.get("wer") is not None]
    if len(wers) < 3:
        return "insufficient"
    first_half = sum(wers[: len(wers) // 2]) / (len(wers) // 2)
    second_half = sum(wers[len(wers) // 2:]) / (len(wers) - len(wers) // 2)
    if second_half < first_half * 0.97:
        return "improving"
    if second_half > first_half * 1.03:
        return "regressing"
    return "plateau"


def _recent_train_failures(window: int = 5) -> int:
    fails = 0
    for log in sorted(LOG_DIR.glob("train_iter*.log"))[-window:]:
        try:
            txt = log.read_text()
            if "Traceback" in txt or "OutOfMemoryError" in txt or "MPS backend out of memory" in txt:
                fails += 1
        except Exception:
            pass
    return fails


def _disk_space_gb() -> float:
    try:
        st = os.statvfs(str(NEXT_TASK_FILE.parent))
        return (st.f_bavail * st.f_frsize) / (1024**3)
    except OSError:
        return -1.0


def plan(state: dict) -> str:
    """Return a markdown task description for the next session."""
    eval_hist = state.get("eval_history", [])
    iter_n = state.get("iteration", 0)
    best_wer = state.get("best_wer")
    last_wer = state.get("last_wer")
    trend = _recent_wer_trend(eval_hist)
    train_fails = _recent_train_failures()
    disk_gb = _disk_space_gb()
    fetch_cv = os.environ.get("SUNO_FETCH_CV") == "1"

    lines: list[str] = [
        "# NEXT_TASK — auto-generated by suno.orchestrator.task_planner",
        "",
        f"_Generated at {datetime.now(timezone.utc).isoformat(timespec='seconds')} after loop iteration {iter_n}._",
        "",
        "## Current state",
        "",
        f"- Iteration: **{iter_n}**",
        f"- Last WER: **{last_wer if last_wer is not None else 'n/a'}**",
        f"- Best WER: **{best_wer if best_wer is not None else 'n/a'}** "
        f"(iter {state.get('best_wer_iteration', 'n/a')})",
        f"- Manifest size: {state.get('data_samples_curated', 'n/a')} samples",
        f"- Recent WER trend: **{trend}**",
        f"- Recent train failures: {train_fails}/5",
        f"- Free disk: {disk_gb:.1f} GB" if disk_gb >= 0 else "- Free disk: unknown",
        f"- Common Voice enabled: {fetch_cv}",
        "",
        "## Recommended next task",
        "",
    ]

    # Decision tree — top-down, first match wins.
    if disk_gb >= 0 and disk_gb < 5:
        lines += [
            "**🚨 LOW DISK — pause loop and free space.**",
            "",
            "Loop will fail next iteration if disk fills. Run:",
            "```",
            "./scripts/stop_loop.sh",
            "du -sh data/hf_cache models/ logs/ | sort -h",
            "```",
            "Then delete old iteration adapters (`models/whisper-small-lora-iter*` except current_best).",
        ]
    elif train_fails >= 3:
        lines += [
            "**🚨 REPEATED TRAINING FAILURES — diagnose before continuing.**",
            "",
            f"{train_fails} of the last 5 iterations failed. Tail the most recent train log:",
            "```",
            "tail -n 100 $(ls -t logs/train_iter*.log | head -1)",
            "```",
            "Common causes: MPS OOM (reduce `SUNO_TRAIN_STEPS` or move to whisper-tiny base), "
            "missing adapter directory, manifest empty, datasets cache corrupted.",
        ]
    elif trend == "plateau" and not fetch_cv:
        lines += [
            "**Enable Common Voice ur and re-train.**",
            "",
            "WER has plateaued for several iterations on FLEURS-only data (~12 hr).",
            "Common Voice adds ~80 hr (CC0, commercial-OK, mostly Indian Urdu — transfer learning is fine for early phase).",
            "",
            "Steps:",
            "1. `huggingface-cli login` (need an HF account, accept CV terms)",
            "2. Set `SUNO_FETCH_CV=1` in `launchd/com.suno.orchestrator.plist`",
            "3. Reload launchd: `./scripts/install_launchd.sh`",
            "4. Next iteration will re-curate manifest with CV included.",
        ]
    elif trend == "plateau" and fetch_cv:
        lines += [
            "**Add a code-switching evaluation set.**",
            "",
            "FLEURS is news Urdu; real Pakistani usage code-switches with English. "
            "Hand-curate 50-100 sentences (or transcribe YouTube clips) and add as a second eval phase. ",
            "This will surface a failure mode the loop currently can't see — likely a ~30-50% WER gap on code-switched audio.",
            "",
            "Where to add: new file `src/suno/orchestrator/phases/evaluate_codeswitch.py`, register in `loop.PHASES`.",
        ]
    elif trend == "regressing":
        lines += [
            "**WER is REGRESSING — rollback and lower learning rate.**",
            "",
            f"Last WER {last_wer} > best {best_wer}. The loop is over-fitting or LR too high.",
            "1. Pause loop: `./scripts/stop_loop.sh`",
            "2. Set base adapter back to `models/current_best/`",
            "3. Lower `--lr` (default 1e-4) to 5e-5 in `whisper_lora_trainer.py`",
            "4. Resume.",
        ]
    elif trend == "improving":
        lines += [
            "**Loop is improving — let it run. Use this session for higher-leverage work.**",
            "",
            "Suggestions, in priority:",
            "1. Email LUMS CSALT for Pakistani Urdu corpus access (see `docs/datasets.md`).",
            "2. Draft model card for `models/current_best/` in `docs/model-cards/`.",
            "3. Set up GitHub Actions nightly eval workflow.",
            "4. Plan TTS training loop (mirror STT loop for VITS).",
        ]
    elif iter_n == 0:
        lines += [
            "**First run — smoke test the pipeline.**",
            "",
            "```",
            "SUNO_LOOP_MAX_ITERS=1 SUNO_TRAIN_STEPS=20 SUNO_EVAL_SAMPLES=5 python -m suno.orchestrator.loop",
            "```",
            "Confirm: data downloads, manifest builds, training runs, eval emits FINAL_WER.",
            "If green, install launchd: `./scripts/install_launchd.sh`.",
        ]
    else:
        lines += [
            "**Insufficient signal — let the loop run a few more iterations.**",
            "",
            "Need at least 3 evals to compute a trend.",
        ]

    lines += [
        "",
        "## How to regenerate",
        "",
        "This file is rewritten at the end of every loop iteration. To regenerate manually:",
        "```",
        "suno-plan",
        "```",
        "",
        "## Standing context (read once, ignore on re-runs)",
        "",
        "- See `CLAUDE.md` for session protocol",
        "- See `docs/decisions/` for locked architectural choices",
        "- See `PROGRESS.md` for full history",
    ]

    return "\n".join(lines) + "\n"


def write_next_task(state: dict) -> Path:
    NEXT_TASK_FILE.write_text(plan(state))
    return NEXT_TASK_FILE


def main() -> None:
    state = state_module.load()
    path = write_next_task(state)
    print(f"wrote {path}")
    print()
    print(path.read_text())


if __name__ == "__main__":
    main()
